#!/usr/bin/env python3
"""Copy selected top-level definitions VERBATIM out of a firmware source file.

usage: extract.py SRC OUT [--prefix TEXT] START_REGEX...
Each START_REGEX[:::END_REGEX] matches the first line of a definition; the copy runs to the
first following line that starts with '}' (function / class / table end).
Used so the simulator draws with the firmware's own code for pieces that live
in files too hardware-bound to compile whole (the board, the voice engine).
"""
import re, sys
args = sys.argv[1:]
src, out = args[0], args[1]
prefix = ""
rest = args[2:]
if rest and rest[0] == "--prefix":
    prefix, rest = rest[1], rest[2:]
lines = open(src).read().split("\n")
chunks = []
covered = set()
for spec in rest:
    pat, _, endpat = spec.partition(":::")
    rx = re.compile(pat)
    endrx = re.compile(endpat or r"^}")
    for i, ln in enumerate(lines):
        if rx.search(ln):
            if i in covered:
                break
            j = i
            while not endrx.search(lines[j]):
                j += 1
            covered.update(range(i, j + 1))
            chunks.append(f'#line {i+1} "{src}"\n' + "\n".join(lines[i:j+1]))
            break
    else:
        sys.exit(f"extract.py: pattern not found in {src}: {pat}")
open(out, "w").write(f"// generated by tools/extract.py from {src}\n" + prefix + "\n" + "\n\n".join(chunks) + "\n")
print(f"{out}: {len(chunks)} chunks")
