#!/usr/bin/env python3
"""Copy CheekoHaptics::EffectAt / EffectName verbatim out of the firmware so
the "Feel the buzzes" list shows the real names without compiling the motor
driver."""
import re, sys
src, out = sys.argv[1], sys.argv[2]
lines = open(src).read().split("\n")
keep, grab = [], False
for ln in lines:
    if re.match(r'^(CheekoHaptics::Effect CheekoHaptics::EffectAt|const char\s*\*\s*CheekoHaptics::EffectName)', ln):
        grab = True
    if grab:
        keep.append(ln)
        if ln.startswith("}"):
            grab = False
            keep.append("")
open(out, "w").write('// generated by tools/extract_haptics.py\n#include "cheeko_haptics.h"\n' + "\n".join(keep))
print(f"extracted {len(keep)} lines")
