#!/usr/bin/env python3
"""Emit a C file defining every asm-labelled blob symbol referenced by the
generated lang_config.h (sound clips embedded by the real build)."""
import re, sys
src, out = sys.argv[1], sys.argv[2]
names = sorted(set(re.findall(r'asm\("([^"]+)"\)', open(src).read())))
with open(out, "w") as f:
    f.write("/* generated by tools/gen_lang_blobs.py */\n")
    for i, n in enumerate(names):
        f.write(f'const char fwsim_blob_{i}[4] __asm__("{n}") = {{0}};\n')
print(f"{len(names)} blob symbols")
